---
- name: create pid directory
  file: path='{{ upstart_pidfile_directory }}' mode=0775 owner='{{ upstart_user }}' group='{{ upstart_group }}' state=directory
  become: yes

- name: create log directory
  file: path='{{ upstart_log_directory }}' mode=0775 owner='{{ upstart_user }}' group='{{ upstart_group }}' state=directory
  become: yes

- name: write prepare conf
  template: src="etc/init/prepare.conf.j2" dest="/etc/init/prepare-{{ upstart_name }}.conf"
  become: yes

- name: write upstart conf
  template: src="etc/init/upstart.conf.j2" dest="/etc/init/{{ upstart_name }}.conf"
  become: yes
